aurora_app/urls.py
from django.conf.urls import include, patterns, url, handler500
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
admin.autodiscover()

handler500 = 'cruiser.views.server_error'

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout', ),
)

urlpatterns += patterns(
    'aurora_app.cruiser.views',
    url(r'^$', 'index', name='index'),
    url(r'^project/(?P<project_id>\d+)$', 'project', name='project'),
    url(r'^project/new$', 'new_project', name='new_project'),
    url(r'^task/(?P<task_id>\d+)$', 'task', name='task'),
    url(r'^task/new$', 'new_task', name='new_task'),
    url(r'^stage/(?P<stage_id>\d+)$', 'stage', name='stage'),
    url(r'^stage/(?P<stage_id>\d+)/(?P<task_id>\d+)/exec$', 'exec_task', name='exec_task'),
    url(r'^stage/new$', 'new_stage', name='new_stage'),
    url(r'^deployment/(?P<deploy_id>\d+)/$', 'monitor', name='deployment_monitor'),
    url(r'^deployment/(?P<deploy_id>\d+)/get_log/$', 'get_log', name='deployment_log'),
    url(r'^deployment/(?P<deploy_id>\d+)/cancel/$', 'cancel', name='cancel_deployment'),
)

urlpatterns += staticfiles_urlpatterns()

aurora_app/deployments/models.py
import time
import os
from datetime import datetime

from flask import url_for, current_app

from ..extensions import db
from ..tasks.models import Task

from .constants import STATUSES, BOOTSTRAP_ALERTS


deployments_tasks_table = db.Table('deployments_tasks', db.Model.metadata,
                                   db.Column('deployment_id', db.Integer,
                                             db.ForeignKey('deployments.id')),
                                   db.Column('task_id', db.Integer,
                                             db.ForeignKey('tasks.id')))


class Deployment(db.Model):
    __tablename__ = "deployments"
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.SmallInteger, default=STATUSES['READY'])
    branch = db.Column(db.String(32), default='master')
    commit = db.Column(db.String(128))
    started_at = db.Column(db.DateTime(), default=datetime.now)
    finished_at = db.Column(db.DateTime())
    code = db.Column(db.Text())
    log = db.Column(db.Text())
    # Relations
    stage_id = db.Column(db.Integer(),
                         db.ForeignKey('stages.id'), nullable=False)
    user_id = db.Column(db.Integer(),
                        db.ForeignKey('users.id'), nullable=False)
    tasks = db.relationship(Task,
                            secondary=deployments_tasks_table,
                            backref="deployments")

    def get_tmp_path(self):
        return os.path.join(current_app.config['AURORA_TMP_DEPLOYMENTS_PATH'],
                            '{0}'.format(self.id))

    def bootstrap_status(self):
        return BOOTSTRAP_ALERTS[self.status]

    def show_status(self):
        for status, number in STATUSES.iteritems():
            if number == self.status:
                return status

    def is_running(self):
        return self.status == STATUSES['RUNNING']

    def show_tasks_list(self):
        template = '<a href="{0}">{1}</a>'
        return ', '.join([template.format(url_for('tasks.view', id=task.id),
                                          task.name) for task in self.tasks])

    def get_log_path(self):
        return os.path.join(self.get_tmp_path(), 'log')

    def get_log_lines(self):
        if self.log:
            return self.log.split('\n')

        path = os.path.join(self.get_tmp_path(), 'log')
        if os.path.exists(path):
            return open(path).readlines()

        return []

    def show_duration(self):
        delta = self.finished_at - self.started_at
        return time.strftime("%H:%M:%S", time.gmtime(delta.seconds))

    def show_commit(self):
        return "{0}".format(self.commit[:10]) if self.commit else ''

    def __init__(self, *args, **kwargs):
        super(Deployment, self).__init__(*args, **kwargs)

        self.code = [self.stage.project.code, self.stage.code]
        for task in self.stage.tasks:
            self.code.append(task.code)
        self.code = '\n'.join(self.code)

aurora_app/deployments/views.py
import json
from datetime import datetime

from flask import (Blueprint, Response, render_template, request, g, redirect,
                   url_for)

from ..utils import get_or_404, notify, build_log_result
from ..extensions import db
from ..decorators import must_be_able_to
from ..stages.models import Stage
from ..tasks.models import Task

from .tasks import deploy
from .models import Deployment
from .constants import STATUSES

deployments = Blueprint('deployments', __name__, url_prefix='/deployments')

current_deployments = {}


@deployments.route('/create/stage/<int:id>', methods=['POST', 'GET'])
@must_be_able_to('create_deployment')
def create(id):
    stage = get_or_404(Stage, id=id)
    clone_id = request.args.get('clone')

    if request.method == 'POST':
        tasks_ids = request.form.getlist('selected')

        if tasks_ids == []:
            return "You must select tasks for deployment."

        tasks = [get_or_404(Task, id=int(task_id)) for task_id in tasks_ids]
        branch = request.form.get('branch')
        commit = request.form.get('commit')

        if not commit and stage.project.get_repo() is not None:
            commit = stage.project.get_last_commit(branch).hexsha

        deployment = Deployment(stage=stage, tasks=tasks,
                                branch=branch, user=g.user, commit=commit,
                                status=STATUSES['RUNNING'])
        db.session.add(deployment)
        db.session.commit()

        deploy(deployment.id)
        return redirect(url_for('deployments.view', id=deployment.id))

    if stage.project.get_or_create_parameter_value('fetch_before_deploy')\
            == 'True':
        # Fetch
        stage.project.fetch()

    branches = stage.project.get_branches()
    if clone_id:
        clone_deployment = get_or_404(Deployment, id=clone_id)

        if clone_deployment.stage.id != stage.id:
            return "Clone deployment should have the same stage."

        # Select clone deployment's branch
        branch = None
        if branches:
            for branch_item in branches:
                if branch_item.name == clone_deployment.branch:
                    branch = branch_item
    else:
        clone_deployment = None
        branch = branches[0] if branches else None

    return render_template('deployments/create.html', stage=stage,
                           branch=branch, clone_deployment=clone_deployment)


@deployments.route('/view/<int:id>')
def view(id):
    deployment = get_or_404(Deployment, id=id)
    return render_template('deployments/view.html', deployment=deployment)


@deployments.route('/code/<int:id>/fabfile.py')
def raw_code(id):
    deployment = get_or_404(Deployment, id=id)
    return Response(deployment.code, mimetype='text/plain')


@deployments.route('/log/<int:id>')
def log(id):
    """
    Function for getting log for deployment in real time.
    Built on server-sent events.
    """
    deployment = get_or_404(Deployment, id=id)
    last_event_id = request.args.get('lastEventId')

    lines = deployment.get_log_lines()
    # If client just connected return all existing log
    result = ['id: {0}'.format(len(lines))]
    if not last_event_id:
        result.extend(build_log_result(lines))
    # else return new lines.
    else:
        new_lines = lines[int(last_event_id):]
        result.extend(build_log_result(new_lines))

    # len(result) == 1 means that no new lines were added
    # and then deployment's log is not updating.
    if len(result) == 1:
        status = deployment.show_status()
        result = 'data: {"event": "finished", "status": "' + status + '"}\n'
    else:
        result = '\n'.join(result)

    return Response(result + '\n\n', mimetype='text/event-stream')


@deployments.route('/stop', methods=['POST'])
def cancel():
    id = request.form.get('id')
    deployment = get_or_404(Deployment, id=id)
    action = 'cancel_deployment'
    if g.user.can(action) and id:
        try:
            current_deployments[id].terminate()
            current_deployments[id].join()
            current_deployments.pop(id)

            deployment.log = '\n'.join(deployment.get_log_lines())
            deployment.log += "Deployment has canceled."
            deployment.finished_at = datetime.now()
            deployment.status = STATUSES['CANCELED']

            db.session.add(deployment)
            db.session.commit()

            message = "Deployment has canceled successfully."
            category = 'success'
        except Exception, e:
            message = "Can't cancel deployment.\n" + \
                      "Error: {0}".format(e.message)
            category = 'error'

        notify(message, category=category, action=action)
        return json.dumps({'error': True if category == 'error' else False})

    notify("You can't execute this action.", category='error', action=action)
    return json.dumps({'error': True})

aurora_app/projects/views.py
import json

from flask import Blueprint, render_template, url_for, redirect, request, g

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify

from .models import Project, ProjectParameter
from .exceptions import ParameterValueError
from .forms import ProjectForm
from .tasks import clone_repository, remove_repository

projects = Blueprint('projects', __name__, url_prefix='/projects')


@projects.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_project')
def create():
    form = ProjectForm()

    if form.validate_on_submit():
        project = Project()
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        project.create_default_params()

        notify(u'Project "{0}" has been created.'.format(project.name),
               category='success', action='create_project')
        return redirect(url_for('projects.view', id=project.id))

    return render_template('projects/create.html', form=form)


@projects.route('/view/<int:id>')
def view(id):
    project = get_or_404(Project, id=id)
    return render_template('projects/view.html', project=project)


@projects.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_project')
def edit(id):
    project = get_or_404(Project, id=id)
    form = ProjectForm(request.form, project)

    if form.validate_on_submit():
        form.params.data = project.params
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        notify(u'Project "{0}" has been updated.'.format(project.name),
               category='success', action='edit_project')
        return redirect(url_for('projects.view', id=id))

    return render_template('projects/edit.html', project=project, form=form)


@projects.route('/delete/<int:id>')
@must_be_able_to('delete_project')
def delete(id):
    project = get_or_404(Project, id=id)

    # Delete stages
    for stage in project.stages:
        db.session.delete(stage)
    # Delete params
    for param in project.params:
        db.session.delete(param)
    db.session.delete(project)
    db.session.commit()
    
    notify(u'Project "{0}" has been deleted.'.format(project.name),
           category='success', action='delete_project')

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))

TASKS = {
    'clone_repository': clone_repository,
    'remove_repository': remove_repository
}


@projects.route('/execute/<int:id>', methods=['POST'])
def execute(id):
    project = get_or_404(Project, id=id)
    action = request.form.get('action')
    if g.user.can(action):
        if action == 'edit_project':
            name, value = request.form.get('name'), request.form.get('value')
            parameter = ProjectParameter.query.filter_by(name=name).first()

            try:
                parameter.set_value(value)
                db.session.add(parameter)
                db.session.commit()
            except ParameterValueError as e:
                notify(e.message, category='error', action='edit_project')
                return json.dumps({'error': True})
        else:
            TASKS[action](project)
        return json.dumps({'error': False})

    notify(u"""You can't execute "{0}.{1}".""".format(project.name, action),
           category='error', action=action, user_id=g.user.id)
    return json.dumps({'error': True})


@projects.route('/commits/<int:id>')
def commits(id):
    project = get_or_404(Project, id=id)
    branch = request.args.get('branch')
    query = request.args.get('query')
    page_limit = int(request.args.get('page_limit'))
    page = int(request.args.get('page'))

    if query:
        commits = project.get_all_commits(branch,
                                          skip=page_limit * page)
    else:
        commits = project.get_commits(branch, max_count=page_limit,
                                      skip=page_limit * (page - 1))

    result = []
    for commit in commits:
        if query and not (query in commit.hexsha or query in commit.message):
            continue
        else:
            result.append({'id': commit.hexsha,
                           'message': commit.message,
                           'title': "{0} - {1}".format(commit.hexsha[:10],
                                                       commit.message)})

    total = project.get_commits_count(branch)
    if query:
        total = len(result)
        result = result[:page_limit]

    return json.dumps({'total': total,
                       'commits': result})


@projects.route('/commits/one/<int:id>/<string:branch>/<string:commit>')
def get_one_commit(id, branch, commit):
    project = get_or_404(Project, id=id)
    commits = project.get_all_commits(branch)
    for item in commits:
        if commit == item.hexsha:
            return json.dumps({'id': item.hexsha,
                               'message': item.message,
                               'title': "{0} - {1}".format(item.hexsha[:10],
                                                           item.message)})
    return 'error', 500


@projects.route('/')
def all():
    projects = Project.query.all()
    return render_template('projects/all.html', projects=projects)

aurora_app/templates/deployments/create.html
{% extends 'frontend/index.html' %}

{% block title %}Deploy | {{ stage }}{% endblock %}

{% block content %}
  <h1>Deploying stage: 
    {% if stage.project %}
      <a href="{{ url_for('projects.view', id=stage.project.id) }}">{{ stage.project.name }}</a> /
    {% endif %} {{ stage.name }}
  </h1>
  <hr />

  <form method='post' action=''>
    <div class='row'>
      <div class='col-lg-4 text-center'>
        <h4>Available tasks:</h4>
        <select class="form-control" name="available" id="available" multiple="multiple" size="10">
          {% for task in stage.tasks %}
            {% if (not clone_deployment) or task not in clone_deployment.tasks %}
              <option value="{{ task.id }}">{{ task.name }}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>

      <div class='col-lg-1 text-center bigger'>
        <ul class='list-unstyled arrows' style='padding-top: 50px;'>
          <li class='pointer'><a id="add">&raquo;</a></li>
          <li>&nbsp;</li>
          <li class='pointer'><a id="remove">&laquo;</a></li>
        </ul>
      </div>

      <div class='col-lg-4 text-center'>
        <h4>Selected tasks:</h4>
        <select class="form-control" name="selected" id="selected" multiple="multiple" size="10">
          {% if clone_deployment %}
            {% for task in clone_deployment.tasks %}
              <option value="{{ task.id }}">{{ task.name }}</option>
            {% endfor %}
          {% endif %}
        </select>
      </div>

      <div class='col-lg-0 text-center bigger'>
        <ul class='list-unstyled arrows' style='padding-top: 50px;'>
          <li class='pointer'><a id="up">&uarr;</a></li>
          <li>&nbsp;</li>
          <li class='pointer'><a id="down">&darr;</a></li>
        </ul>
      </div>
    </div>

    {% if branch %}
      <div class='row'>
        <div class='col-lg-4 text-center'>
          <h4>Branch:</h4>
          <select class="form-control" name="branch" id="branches">
            {% for branch_item in stage.project.get_branches() %}
              <option value="{{ branch_item.name }}"
              {% if branch == branch_item %}
                selected
              {% endif %}
              >{{ branch_item.name }}</option>
            {% endfor %}
          </select>
        </div>

        <div class='col-lg-6 text-center'>
          <h4>Commit:</h4>
          <input type='hidden' id="commits" class='wider' name='commit' {% if clone_deployment %}value='{{ clone_deployment.commit }}'{% endif %} />
        </div>
      </div>
    {% endif %}

    <hr />

    <button type='submit' id="deploy" class='btn btn-default'>Deploy</button>

  </form>
{% endblock %}


{% block css %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('static', filename='select2/select2.css') }}" />
{% endblock %}

{% block js %}
  {{ super() }}
  <script src="{{ url_for('static', filename='select2/select2.min.js') }}"></script>

  <script>
    $(function() {
      // Init commits select
      $("#commits").select2({
        placeholder: "Select a commit",
        ajax: {
          url: "{{ url_for('projects.commits', id=stage.project.id) }}",
          dataType: 'json',
          quietMillis: 100,
          data: function (term, page) { // page is the one-based page number tracked by Select2
              return {
                  query: term, //search term
                  page_limit: 10, // page size
                  page: page, // page number
                  branch: $('#branches :selected').text() // selected branch
              };
          },
          results: function (data, page) {
              var more = (page * 10) < data.total; // whether or not there are more results available

              // notice we return the value of more so Select2 knows if more results can be loaded
              return {results: data.commits, more: more};
          }
        },
        {% if clone_deployment and clone_deployment.commit %}
          initSelection: function(element, callback) {
            var id = $(element).val();
            if (id !== "") {
                $.ajax("{{ url_for('projects.get_one_commit', id=stage.project.id, branch=branch.name, commit=clone_deployment.commit) }}").done(function(data) { callback(JSON.parse(data)); });
            }
          },
        {% endif %}
        formatResult: function(commit) {
          return commit.title;
        },
        formatSelection: function(commit) {
          return commit.title;
        }
      });
      // Form hook
      $("#deploy").click(function() {
        $("#selected option").each(function() {
          $(this).attr("selected", "selected"); 
        });
      });
      // From: http://www.designchemical.com/blog/index.php/jquery/change-order-multiple-select-lists-using-jquery/
      // Add button hook
      $("#add").click(function() {
        $('#available option:selected').each(function() {
          $('#selected').append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
          $(this).remove();
        });
      });
      // Remove button hook
      $("#remove").click(function() {
        $('#selected option:selected').each(function() {
          $('#available').append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
          $(this).remove();
        });
      });
      // Up button hook
      $('#up').click(function() {
        $('#selected option:selected').each( function() {
          var newPos = $('#selected option').index(this) - 1;
          if (newPos > -1) {
            $('#selected option').eq(newPos).before("<option value='"+$(this).val()+"' selected='selected'>"+$(this).text()+"</option>");
            $(this).remove();
          }
        });
      });
      // Down button hook
      $('#down').click(function() {
        var countOptions = $('#selected option').size();
        $('#selected option:selected').each(function() {
          var newPos = $('#selected option').index(this) + 1;
          if (newPos < countOptions) {
            $('#selected option').eq(newPos).after("<option value='"+$(this).val()+"' selected='selected'>"+$(this).text()+"</option>");
            $(this).remove();
          }
        });
      });
    });
  </script>
{% endblock %}

aurora_app/templates/deployments/deployment.html
<div class="alert alert-{{ deployment.bootstrap_status() }}">
  <div class='row'>
    <div class='col-lg-4'>
      <a href="{{ url_for('deployments.view', id=deployment.id) }}">
        <strong>#{{ deployment.id }} - {{ deployment.show_status() }}</strong>
      </a>
      {% include 'deployments/deployment_actions.html' %}
    </div>
  </div>
  <div class='row'>
    <div class="col-lg-4">
      <ul class='list-unstyled'>
        <li>
          <strong>Stage:</strong> <a href="{{ url_for('stages.view', id=deployment.stage.id) }}">{{ deployment.stage }}</a>
        </li>
        <li><strong>Branch:</strong> {{ deployment.branch }}</li>
        <li>
          <strong>Commit:</strong> {{ deployment.show_commit() }}
        </li>
      </ul>
    </div>
    <div class="col-lg-4">
      <ul class='list-unstyled'>
        <li><strong>Duration:</strong>
          {% if deployment.finished_at %}
            {{ deployment.show_duration() }}
          {% endif %}
        </li>
        <li><strong>Started at:</strong> {{ deployment.started_at.strftime('%Y-%m-%d %H:%M:%S') }}</li>
        <li><strong>Finished at:</strong>
          {% if deployment.finished_at %}
            {{ deployment.finished_at.strftime('%Y-%m-%d %H:%M:%S') }}
          {% endif %}
        </li>
      </ul>
    </div>    
    <div class='col-lg-3'>
      <ul class='list-unstyled'>
        <li><strong>User:</strong> <a href="{{ url_for('users.view', id=deployment.user.id) }}">{{ deployment.user.username }}</a></li>
        <li><strong>Tasks:</strong> {{ deployment.show_tasks_list()|safe }}</li>
      </ul>
    </div>
  </div>
</div>

aurora_app/templates/deployments/deployment_actions.html
{% if g.user.can('create_deployment') %}
  <a href='{{ url_for('deployments.create', id=deployment.stage.id, clone=deployment.id) }}' title='Repeat'>
    <i class='glyphicon glyphicon-repeat'></i>
  </a>
{% endif %}

{% if deployment.is_running() and g.user.can('cancel_deployment') %}
  <a id="cancel_deployment_button" data-id="{{ deployment.id }}" title='Cancel'>
    <i class='glyphicon glyphicon-ban-circle'></i>
  </a>
{% endif %}

aurora_app/templates/deployments/log.html
<ul class='list-unstyled' style='margin-left: 5px;'>
  {% for line in lines %}
    <li>{{ line }}</li>
  {% endfor %}
</ul>

aurora_app/templates/deployments/view.html
{% extends 'frontend/index.html' %}

{% block title %}#{{ deployment.id }} - {{ deployment.stage }} {% endblock %}

{% block content %}
  <ul class='list-unstyled list-inline'>
    <li>
      <h1>#{{ deployment.id }} -
          {% if deployment.stage.project %}
            <a href="{{ url_for('projects.view', id=deployment.stage.project.id) }}">{{ deployment.stage.project.name }}</a> /
          {% endif %} <a href="{{ url_for('stages.view', id=deployment.stage.id) }}">{{ deployment.stage.name }}</a>
      </h1>
    </li>
    <li><h3>- <span id="deployment_status">{{ deployment.show_status() }}</span></h3></li>
  </ul>

  <hr />

  <div class='well'>
    <div class='row'>
      <div class='col-lg-2'>
        <ul class='list-unstyled'>
          <li>
            <strong>Actions:</strong>
            {% include 'deployments/deployment_actions.html' %}
          </li>
        </ul>
      </div>
    </div>
    <div class='row'>
      <div class="col-lg-3">
        <ul class='list-unstyled'>
          <li>
            <strong>Code:</strong> <a href="{{ url_for('deployments.raw_code', id=deployment.id) }}">Raw</a>
          </li>
          <li><strong>Branch:</strong> {{ deployment.branch }}</li>
          <li>
            <strong>Commit:</strong> {{ deployment.show_commit() }}
          </li>
        </ul>
      </div>
      <div class='col-lg-4'>
        <ul class='list-unstyled'>
          <li><strong>Duration:</strong>
            {% if deployment.finished_at %}
              {{ deployment.show_duration() }}
            {% endif %}
          </li>
          <li><strong>Started at:</strong> {{ deployment.started_at.strftime('%Y-%m-%d %H:%M:%S') }}</li>
          <li><strong>Finished at:</strong>
            {% if deployment.finished_at %}
              {{ deployment.finished_at.strftime('%Y-%m-%d %H:%M:%S') }}
            {% endif %}
          </li>
        </ul>
      </div>
      <div class='col-lg-3'>
        <ul class='list-unstyled'>
          <li><strong>User:</strong> <a href="{{ url_for('users.view', id=deployment.user.id) }}">{{ deployment.user.username }}</a></li>
          <li><strong>Tasks:</strong> {{ deployment.show_tasks_list()|safe }}</li>
        </ul>
      </div>
    </div>
  </div>

  <p><strong>Log:</strong>
    {% if not deployment.log %}
      <button id='follow' class='btn btn-default btn-small'>Follow</button>
    {% endif %}
  </p>
  <div id="log" class='well' style='height: 300px; overflow: auto'>
    <ul class='list-unstyled'>
      {% if not deployment.is_running() %}
        {% for line in deployment.get_log_lines() %}
          <li>{{ line }}</li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
{% endblock %}

{% block js %}
  {{ super() }}

  <script>
    {% if deployment.is_running() %}
      $(function () {
        var follow = false;
        $("#follow").click(function() {
          if (follow) {
            $("#follow").text('Follow');
            follow = false;
          } else {
            $("#follow").text('Unfollow');
            follow = true;
          }
        });

        var eventSource = new EventSource("{{ url_for('deployments.log', id=deployment.id) }}");
        eventSource.addEventListener("message",  function(e) {
          var data = $.parseJSON(e.data);
          var log = $("#log");

          if (data.message) {
            log.find('ul').append("<li>" + data.message + "</li>");
          }

          if (follow) {
            log.scrollTop(log[0].scrollHeight);
          }

          if (data.event && data.event == "finished") {
            $("#deployment_status").text(data.status);
            $("#cancel_deployment_button").hide();
            $("#follow").hide();
            eventSource.close();
          }
        });
      });
    {% endif %}
  </script>
{% endblock %}