aurora_app/urls.py
from django.conf.urls import include, patterns, url, handler500
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
admin.autodiscover()

handler500 = 'cruiser.views.server_error'

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout', ),
)

urlpatterns += patterns(
    'aurora_app.cruiser.views',
    url(r'^$', 'index', name='index'),
    url(r'^project/(?P<project_id>\d+)$', 'project', name='project'),
    url(r'^project/new$', 'new_project', name='new_project'),
    url(r'^task/(?P<task_id>\d+)$', 'task', name='task'),
    url(r'^task/new$', 'new_task', name='new_task'),
    url(r'^stage/(?P<stage_id>\d+)$', 'stage', name='stage'),
    url(r'^stage/(?P<stage_id>\d+)/(?P<task_id>\d+)/exec$', 'exec_task', name='exec_task'),
    url(r'^stage/new$', 'new_stage', name='new_stage'),
    url(r'^deployment/(?P<deploy_id>\d+)/$', 'monitor', name='deployment_monitor'),
    url(r'^deployment/(?P<deploy_id>\d+)/get_log/$', 'get_log', name='deployment_log'),
    url(r'^deployment/(?P<deploy_id>\d+)/cancel/$', 'cancel', name='cancel_deployment'),
)

urlpatterns += staticfiles_urlpatterns()

aurora_app/projects/models.py
import os

from git import Repo
from flask import current_app

from ..extensions import db
from ..stages.models import Stage

from .constants import DEFAULT_PARAMETERS, PARAMETER_TYPES
from .exceptions import ParameterValueError


class Project(db.Model):
    __tablename__ = "projects"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), nullable=False)
    description = db.Column(db.String(128), default='')
    repository_path = db.Column(db.String(128), default='')
    code = db.Column(db.Text(), default='')
    # Relations
    stages = db.relationship(Stage, backref="project")
    params = db.relationship("ProjectParameter", backref="project")

    def __init__(self, *args, **kwargs):
        super(Project, self).__init__(*args, **kwargs)

    def create_default_params(self):
        for parameter_name in DEFAULT_PARAMETERS.keys():
            self.create_default_parameter(parameter_name)

    def create_default_parameter(self, name):
        parameter_dict = DEFAULT_PARAMETERS[name]
        parameter_dict['name'] = name
        parameter_dict['project_id'] = self.id
        parameter = ProjectParameter(**parameter_dict)
        db.session.add(parameter)
        db.session.commit()
        return parameter

    def get_or_create_parameter_value(self, name):
        for parameter in self.params:
            if parameter.name == name:
                return parameter.value

        return self.create_default_parameter(name).value

    def get_name_for_path(self):
        return self.name.lower().replace(' ', '_')

    def get_path(self):
        """Returns path of project's git repository on local machine."""
        return os.path.join(current_app.config['AURORA_PROJECTS_PATH'],
                            self.get_name_for_path())

    def repository_folder_exists(self):
        return os.path.exists(self.get_path())

    def get_repo(self):
        if self.repository_folder_exists():
            return Repo.init(self.get_path())
        return None

    def get_branches(self):
        repo = self.get_repo()
        if repo:
            return [ref for ref in repo.refs if ref.name != 'origin/HEAD']
        return None

    def get_commits(self, branch, max_count, skip):
        repo = self.get_repo()
        if repo:
            return repo.iter_commits(branch, max_count=max_count,
                                     skip=skip)
        return None

    def get_all_commits(self, branch, skip=None):
        repo = self.get_repo()
        if repo:
            return repo.iter_commits(branch, skip=skip)
        return None

    def get_last_commit(self, branch):
        repo = self.get_repo()
        if repo:
            return repo.iter_commits(branch).next()
        return None

    def get_commits_count(self, branch):
        repo = self.get_repo()
        if repo:
            return reduce(lambda x, _: x + 1, repo.iter_commits(branch), 0)
        return None

    def fetch(self):
        repo = self.get_repo()
        if repo:
            return repo.git.fetch()

    def __repr__(self):
        return self.name


class ProjectParameter(db.Model):
    __tablename__ = "project_parameters"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    value = db.Column(db.String(128), nullable=False)
    type = db.Column(db.SmallInteger, nullable=False)
    # Relations
    project_id = db.Column(db.Integer(), db.ForeignKey('projects.id'),
                           nullable=False)

    def set_value(self, value):
        if self.type == PARAMETER_TYPES['BOOL']:
            values = ['True', 'False']
            if value not in values:
                raise ParameterValueError('Wrong value for bool parameter.')
        elif self.type == PARAMETER_TYPES['INT']:
            try:
                int(value)
            except ValueError:
                raise ParameterValueError('Wrong value for int parameter.')

        self.value = value

    def __init__(self, *args, **kwargs):
        super(ProjectParameter, self).__init__(*args, **kwargs)

aurora_app/projects/forms.py
from flask.ext.wtf import Form
from wtforms.ext.sqlalchemy.orm import model_form

from ..extensions import db

from .models import Project

ProjectForm = model_form(Project, db.session, Form)

aurora_app/projects/views.py
import json

from flask import Blueprint, render_template, url_for, redirect, request, g

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify

from .models import Project, ProjectParameter
from .exceptions import ParameterValueError
from .forms import ProjectForm
from .tasks import clone_repository, remove_repository

projects = Blueprint('projects', __name__, url_prefix='/projects')


@projects.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_project')
def create():
    form = ProjectForm()

    if form.validate_on_submit():
        project = Project()
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        project.create_default_params()

        notify(u'Project "{0}" has been created.'.format(project.name),
               category='success', action='create_project')
        return redirect(url_for('projects.view', id=project.id))

    return render_template('projects/create.html', form=form)


@projects.route('/view/<int:id>')
def view(id):
    project = get_or_404(Project, id=id)
    return render_template('projects/view.html', project=project)


@projects.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_project')
def edit(id):
    project = get_or_404(Project, id=id)
    form = ProjectForm(request.form, project)

    if form.validate_on_submit():
        form.params.data = project.params
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        notify(u'Project "{0}" has been updated.'.format(project.name),
               category='success', action='edit_project')
        return redirect(url_for('projects.view', id=id))

    return render_template('projects/edit.html', project=project, form=form)


@projects.route('/delete/<int:id>')
@must_be_able_to('delete_project')
def delete(id):
    project = get_or_404(Project, id=id)

    # Delete stages
    for stage in project.stages:
        db.session.delete(stage)
    # Delete params
    for param in project.params:
        db.session.delete(param)
    db.session.delete(project)
    db.session.commit()
    
    notify(u'Project "{0}" has been deleted.'.format(project.name),
           category='success', action='delete_project')

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))

TASKS = {
    'clone_repository': clone_repository,
    'remove_repository': remove_repository
}


@projects.route('/execute/<int:id>', methods=['POST'])
def execute(id):
    project = get_or_404(Project, id=id)
    action = request.form.get('action')
    if g.user.can(action):
        if action == 'edit_project':
            name, value = request.form.get('name'), request.form.get('value')
            parameter = ProjectParameter.query.filter_by(name=name).first()

            try:
                parameter.set_value(value)
                db.session.add(parameter)
                db.session.commit()
            except ParameterValueError as e:
                notify(e.message, category='error', action='edit_project')
                return json.dumps({'error': True})
        else:
            TASKS[action](project)
        return json.dumps({'error': False})

    notify(u"""You can't execute "{0}.{1}".""".format(project.name, action),
           category='error', action=action, user_id=g.user.id)
    return json.dumps({'error': True})


@projects.route('/commits/<int:id>')
def commits(id):
    project = get_or_404(Project, id=id)
    branch = request.args.get('branch')
    query = request.args.get('query')
    page_limit = int(request.args.get('page_limit'))
    page = int(request.args.get('page'))

    if query:
        commits = project.get_all_commits(branch,
                                          skip=page_limit * page)
    else:
        commits = project.get_commits(branch, max_count=page_limit,
                                      skip=page_limit * (page - 1))

    result = []
    for commit in commits:
        if query and not (query in commit.hexsha or query in commit.message):
            continue
        else:
            result.append({'id': commit.hexsha,
                           'message': commit.message,
                           'title': "{0} - {1}".format(commit.hexsha[:10],
                                                       commit.message)})

    total = project.get_commits_count(branch)
    if query:
        total = len(result)
        result = result[:page_limit]

    return json.dumps({'total': total,
                       'commits': result})


@projects.route('/commits/one/<int:id>/<string:branch>/<string:commit>')
def get_one_commit(id, branch, commit):
    project = get_or_404(Project, id=id)
    commits = project.get_all_commits(branch)
    for item in commits:
        if commit == item.hexsha:
            return json.dumps({'id': item.hexsha,
                               'message': item.message,
                               'title': "{0} - {1}".format(item.hexsha[:10],
                                                           item.message)})
    return 'error', 500


@projects.route('/')
def all():
    projects = Project.query.all()
    return render_template('projects/all.html', projects=projects)

aurora_app/stages/views.py
from flask import (Blueprint, render_template, request, redirect, url_for,
                   Response)

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify
from ..projects.models import Project
from ..deployments.models import Deployment

from .forms import StageForm
from .models import Stage

stages = Blueprint('stages', __name__, url_prefix='/stages')


@stages.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_stage')
def create():
    project_id = request.args.get('project_id', None)
    project = get_or_404(Project, id=project_id) if project_id else None
    form = StageForm(project=project)

    if form.validate_on_submit():
        stage = Stage()
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been created.'.format(stage),
               category='success', action='create_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/create.html', form=form, id=project_id)


@stages.route('/view/<int:id>')
def view(id):
    stage = get_or_404(Stage, id=id)
    return render_template('stages/view.html', stage=stage)


@stages.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_stage')
def edit(id):
    stage = get_or_404(Stage, id=id)
    form = StageForm(request.form, stage)

    if form.validate_on_submit():
        # Since we don't show deployments in form, we need to set them here.
        form.deployments.data = stage.deployments
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been updated.'.format(stage),
               category='success', action='edit_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/edit.html', stage=stage, form=form)


@stages.route('/delete/<int:id>')
@must_be_able_to('delete_stage')
def delete(id):
    stage = get_or_404(Stage, id=id)

    project_id = stage.project.id if stage.project else None

    notify(u'Stage "{0}" has been deleted.'.format(stage),
           category='success', action='delete_stage')

    db.session.delete(stage)
    db.session.commit()

    if project_id:
        return redirect(url_for('projects.view', id=project_id))

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@stages.route('/')
def all():
    stages = Stage.query.all()
    return render_template('stages/all.html', stages=stages)


@stages.route('/export/<int:id>/fabfile.py')
def export(id):
    stage = get_or_404(Stage, id=id)

    deployment = Deployment(stage=stage, tasks=stage.tasks)
    return Response(deployment.code, mimetype='application/python')

aurora_app/templates/projects/all.html
{% extends 'frontend/index.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
  <ul class='list-unstyled list-inline'>
    <li><h1>Projects</h1></li>
    {% if g.user.can('create_project') %}
      <li><a href="{{ url_for('projects.create') }}">New</a></li>
    {% endif %}
  </ul>
  <hr />

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      {% for project in projects %}
          <tr>
            <td><a href="{{ url_for('projects.view', id=project.id) }}">{{ project.name }}</a></td>
            <td>
              {{ project.description }}
            </td>
            <td class="small-width"><a href="{{ url_for('projects.edit', id=project.id) }}">Edit</a></td>
            <td class="small-width"><a href="{{ url_for('projects.delete', id=project.id, next=url_for('projects.all')) }}" class='delete'>Delete</a></td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block js %}
  {{ super() }}

  <script src="{{ url_for('static', filename='aurora/js/delete_handler.js') }}"></script>
{% endblock %}

aurora_app/templates/projects/create.html
{% extends 'frontend/index.html' %}

{% block title %}Create a new project{% endblock %}

{% block content %}
  <h1>Create a new project</h1>
  <hr />
  {% include 'projects/form.html' %}
{% endblock %}

aurora_app/templates/projects/edit.html
{% extends 'frontend/index.html' %}

{% block title %}Edit | {{ project.name }}{% endblock %}

{% block content %}
  <h1>Editing project: {{ project.name }}</h1>
  <hr />
  {% include 'projects/form.html' %}
{% endblock %}

aurora_app/templates/projects/form.html
{% import 'helpers/errors.html' as errors %}

<form method="post" action="">
  <fieldset>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class="form-control") }}

      {{ errors.show(form.name) }}
    </div>

    <div class="form-group">
      {{ form.description.label }}
      {{ form.description(class="form-control input-xlarge") }}

      {{ errors.show(form.description) }}
    </div>

    <div class="form-group">
      {{ form.repository_path.label }}
      {{ form.repository_path(class="form-control input-xlarge") }}

      {{ errors.show(form.repository_path) }}
    </div>

    <div class="form-group">
      {{ form.code.label }}
      {{ form.code(class="form-control") }}

      {{ errors.show(form.code) }}
    </div>

    <div class="form-group">
      {{ form.stages.label }}
      {{ form.stages(class="form-control") }}

      {{ errors.show(form.stages) }}
    </div>

    <button class='btn btn-default'>Submit</button>
  </fieldset>
</form>

{% include 'helpers/codemirror.html' %}

aurora_app/templates/projects/view.html
{% import 'helpers/recent_deployments.html' as recent_deployments %}

{% extends 'frontend/index.html' %}

{% block title %}{{ project.name }}{% endblock %}

{% block content %}
  <ul class='list-unstyled list-inline'>
    <li><h1>{{ project.name }}</h1></li>
    {% if g.user.can('edit_project') %}
      <li><a href="{{ url_for('projects.edit', id=project.id) }}">Edit</a></li>
    {% endif %}
    {% if g.user.can('delete_project') %}
      <li><a id="delete">Delete</a></li>
    {% endif %}
  </ul>

  <hr />

  <div class='well'>
    <p><strong>Description:</strong> {{ project.description }}</p>
    <p><strong>Repository path:</strong> {{ project.repository_path }}
      <span id="actions">
        <a data-action="clone_repository" data-toggle='tooltip' data-placement='top' data-original-title="Clone repository"><i class='glyphicon glyphicon-download-alt'></i></a>
        <a data-action="remove_repository" data-toggle='tooltip' data-placement='top' data-original-title="Remove repository"><i class='glyphicon glyphicon-remove'></i></a>
      </span>
    </p>
  </div>

  <p><strong>Code:</strong></p>
  <pre><code lang="python">{{ project.code }}</code></pre>

  <p><strong>Parameters:</strong></p>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      {% for parameter in project.params %}
          <tr>
            <td>{{ parameter.name }}</td>
            <td data-parameter-name="{{ parameter.name }}" class="parameter-value">{{ parameter.value }}</td>
          </tr>
      {% endfor %}
    </tbody>
  </table>

  <ul class='list-unstyled list-inline'>
    <li><h4>Stages</h4></li>
    {% if g.user.can('create_stage') %}
      <li><a href="{{ url_for('stages.create', project_id=project.id) }}">New</a></li>
    {% endif %}
  </ul>

  {% if project.stages %}
    <ul>
      {% for stage in project.stages %}
        <li><a href="{{ url_for('stages.view', id=stage.id) }}">{{ stage.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p class='alert'>
      No available stages.
    </p>
  {% endif %}

  {{ recent_deployments.show(get_recent_deployments(project)) }}
{% endblock %}

{% block js %}
  {{ super() }}

  <script>
    $(function() {
      // Enable actions tooltips
      $('#actions').tooltip({
        selector: "a[data-toggle=tooltip]"
      });
      // Show available actions
      {% if project.repository_folder_exists() %}
        $("#actions a[data-action='remove_repository']").show();
      {% else %}
        {% if project.repository_path %}
          $("#actions a[data-action='clone_repository']").show();
        {% endif %}
      {% endif %}
      // Actions hook
      $("#actions a[data-action]").click(function() {
        var _this = $(this);
        var icon = $(this).find('i').attr('class');
        var action = $(this).data('action');

        // Show refresh icon
        $(this).find('i').attr('class', 'icon-refresh');

        $.ajax({
          url:'{{ url_for('projects.execute', id=project.id) }}',
          data: {'action': action},
          type:'post',
          success: function(data) {
            // Return old icon
            $(_this).find('i').attr('class', icon);

            var result = $.parseJSON(data);
            if (!result.error) {
              $(_this).hide();
              // Actions after result
              if (action == 'clone_repository') {
                // Show 'remove_repository' button.
                $("#actions a[data-action='remove_repository']").show();
              }
              if (action == 'remove_repository') {
                // Show 'clone_repository' button.
                $("#actions a[data-action='clone_repository']").show();
              }
            }
          }
        });
      });
      // Delete button hook
      $("#delete").click(function() {
        if (confirm("Are you sure?\nAll stages will be removed.")) {
          document.location.href = "{{ url_for('projects.delete', id=project.id) }}";
        }
      });
      {% if g.user.can('edit_project') %}
        // Params hooks
        $(".parameter-value").click(function() {
          var _this = this;
          if ($(_this).data('editing') != 'true') {
            $(_this).data('editing', 'true');
            var value = $(_this).text();
            $(_this).html("<input type='text' value='" + value + "'/>");
            var input = $(_this).find('input');
            input.focus();
            input.focusout(function() {
              $.ajax({
                  url:'{{ url_for('projects.execute', id=project.id) }}',
                  data: {'action': 'edit_project',
                         'name': $(_this).data('parameter-name'),
                         'value': input.val()
                  },
                  type:'post',
                  success: function(data) {
                    if ($.parseJSON(data).error != true) {
                      $(_this).data('editing', 'false');
                      $(_this).html(input.val());
                    }
                  }
                });
            });
          }
        });
      {% endif %}
    });
  </script>
{% endblock %}