aurora_app/urls.py
from django.conf.urls import include, patterns, url, handler500
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
admin.autodiscover()

handler500 = 'cruiser.views.server_error'

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout', ),
)

urlpatterns += patterns(
    'aurora_app.cruiser.views',
    url(r'^$', 'index', name='index'),
    url(r'^project/(?P<project_id>\d+)$', 'project', name='project'),
    url(r'^project/new$', 'new_project', name='new_project'),
    url(r'^task/(?P<task_id>\d+)$', 'task', name='task'),
    url(r'^task/new$', 'new_task', name='new_task'),
    url(r'^stage/(?P<stage_id>\d+)$', 'stage', name='stage'),
    url(r'^stage/(?P<stage_id>\d+)/(?P<task_id>\d+)/exec$', 'exec_task', name='exec_task'),
    url(r'^stage/new$', 'new_stage', name='new_stage'),
    url(r'^deployment/(?P<deploy_id>\d+)/$', 'monitor', name='deployment_monitor'),
    url(r'^deployment/(?P<deploy_id>\d+)/get_log/$', 'get_log', name='deployment_log'),
    url(r'^deployment/(?P<deploy_id>\d+)/cancel/$', 'cancel', name='cancel_deployment'),
)

urlpatterns += staticfiles_urlpatterns()

aurora_app/stages/models.py
from ..extensions import db
from ..tasks.models import Task
from ..deployments.models import Deployment

stages_tasks_table = db.Table('stages_tasks', db.Model.metadata,
                              db.Column('stage_id', db.Integer,
                                        db.ForeignKey('stages.id')),
                              db.Column('task_id', db.Integer,
                                        db.ForeignKey('tasks.id')))


class Stage(db.Model):
    __tablename__ = "stages"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), nullable=False)
    code = db.Column(db.Text(), default='')
    # Relations
    project_id = db.Column(db.Integer(), db.ForeignKey('projects.id'))
    deployments = db.relationship(Deployment, backref="stage")
    tasks = db.relationship(Task,
                            secondary=stages_tasks_table,
                            backref="stages")

    def __init__(self, *args, **kwargs):
        super(Stage, self).__init__(*args, **kwargs)

    def __repr__(self):
        return u"{0} / {1}".format(self.project.name, self.name) if \
            self.project else self.name

aurora_app/stages/forms.py
from flask.ext.wtf import Form
from wtforms.ext.sqlalchemy.orm import model_form

from ..extensions import db

from .models import Stage

StageForm = model_form(Stage, db.session, Form)

aurora_app/deployments/views.py
import json
from datetime import datetime

from flask import (Blueprint, Response, render_template, request, g, redirect,
                   url_for)

from ..utils import get_or_404, notify, build_log_result
from ..extensions import db
from ..decorators import must_be_able_to
from ..stages.models import Stage
from ..tasks.models import Task

from .tasks import deploy
from .models import Deployment
from .constants import STATUSES

deployments = Blueprint('deployments', __name__, url_prefix='/deployments')

current_deployments = {}


@deployments.route('/create/stage/<int:id>', methods=['POST', 'GET'])
@must_be_able_to('create_deployment')
def create(id):
    stage = get_or_404(Stage, id=id)
    clone_id = request.args.get('clone')

    if request.method == 'POST':
        tasks_ids = request.form.getlist('selected')

        if tasks_ids == []:
            return "You must select tasks for deployment."

        tasks = [get_or_404(Task, id=int(task_id)) for task_id in tasks_ids]
        branch = request.form.get('branch')
        commit = request.form.get('commit')

        if not commit and stage.project.get_repo() is not None:
            commit = stage.project.get_last_commit(branch).hexsha

        deployment = Deployment(stage=stage, tasks=tasks,
                                branch=branch, user=g.user, commit=commit,
                                status=STATUSES['RUNNING'])
        db.session.add(deployment)
        db.session.commit()

        deploy(deployment.id)
        return redirect(url_for('deployments.view', id=deployment.id))

    if stage.project.get_or_create_parameter_value('fetch_before_deploy')\
            == 'True':
        # Fetch
        stage.project.fetch()

    branches = stage.project.get_branches()
    if clone_id:
        clone_deployment = get_or_404(Deployment, id=clone_id)

        if clone_deployment.stage.id != stage.id:
            return "Clone deployment should have the same stage."

        # Select clone deployment's branch
        branch = None
        if branches:
            for branch_item in branches:
                if branch_item.name == clone_deployment.branch:
                    branch = branch_item
    else:
        clone_deployment = None
        branch = branches[0] if branches else None

    return render_template('deployments/create.html', stage=stage,
                           branch=branch, clone_deployment=clone_deployment)


@deployments.route('/view/<int:id>')
def view(id):
    deployment = get_or_404(Deployment, id=id)
    return render_template('deployments/view.html', deployment=deployment)


@deployments.route('/code/<int:id>/fabfile.py')
def raw_code(id):
    deployment = get_or_404(Deployment, id=id)
    return Response(deployment.code, mimetype='text/plain')


@deployments.route('/log/<int:id>')
def log(id):
    """
    Function for getting log for deployment in real time.
    Built on server-sent events.
    """
    deployment = get_or_404(Deployment, id=id)
    last_event_id = request.args.get('lastEventId')

    lines = deployment.get_log_lines()
    # If client just connected return all existing log
    result = ['id: {0}'.format(len(lines))]
    if not last_event_id:
        result.extend(build_log_result(lines))
    # else return new lines.
    else:
        new_lines = lines[int(last_event_id):]
        result.extend(build_log_result(new_lines))

    # len(result) == 1 means that no new lines were added
    # and then deployment's log is not updating.
    if len(result) == 1:
        status = deployment.show_status()
        result = 'data: {"event": "finished", "status": "' + status + '"}\n'
    else:
        result = '\n'.join(result)

    return Response(result + '\n\n', mimetype='text/event-stream')


@deployments.route('/stop', methods=['POST'])
def cancel():
    id = request.form.get('id')
    deployment = get_or_404(Deployment, id=id)
    action = 'cancel_deployment'
    if g.user.can(action) and id:
        try:
            current_deployments[id].terminate()
            current_deployments[id].join()
            current_deployments.pop(id)

            deployment.log = '\n'.join(deployment.get_log_lines())
            deployment.log += "Deployment has canceled."
            deployment.finished_at = datetime.now()
            deployment.status = STATUSES['CANCELED']

            db.session.add(deployment)
            db.session.commit()

            message = "Deployment has canceled successfully."
            category = 'success'
        except Exception, e:
            message = "Can't cancel deployment.\n" + \
                      "Error: {0}".format(e.message)
            category = 'error'

        notify(message, category=category, action=action)
        return json.dumps({'error': True if category == 'error' else False})

    notify("You can't execute this action.", category='error', action=action)
    return json.dumps({'error': True})

aurora_app/stages/views.py
from flask import (Blueprint, render_template, request, redirect, url_for,
                   Response)

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify
from ..projects.models import Project
from ..deployments.models import Deployment

from .forms import StageForm
from .models import Stage

stages = Blueprint('stages', __name__, url_prefix='/stages')


@stages.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_stage')
def create():
    project_id = request.args.get('project_id', None)
    project = get_or_404(Project, id=project_id) if project_id else None
    form = StageForm(project=project)

    if form.validate_on_submit():
        stage = Stage()
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been created.'.format(stage),
               category='success', action='create_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/create.html', form=form, id=project_id)


@stages.route('/view/<int:id>')
def view(id):
    stage = get_or_404(Stage, id=id)
    return render_template('stages/view.html', stage=stage)


@stages.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_stage')
def edit(id):
    stage = get_or_404(Stage, id=id)
    form = StageForm(request.form, stage)

    if form.validate_on_submit():
        # Since we don't show deployments in form, we need to set them here.
        form.deployments.data = stage.deployments
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been updated.'.format(stage),
               category='success', action='edit_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/edit.html', stage=stage, form=form)


@stages.route('/delete/<int:id>')
@must_be_able_to('delete_stage')
def delete(id):
    stage = get_or_404(Stage, id=id)

    project_id = stage.project.id if stage.project else None

    notify(u'Stage "{0}" has been deleted.'.format(stage),
           category='success', action='delete_stage')

    db.session.delete(stage)
    db.session.commit()

    if project_id:
        return redirect(url_for('projects.view', id=project_id))

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@stages.route('/')
def all():
    stages = Stage.query.all()
    return render_template('stages/all.html', stages=stages)


@stages.route('/export/<int:id>/fabfile.py')
def export(id):
    stage = get_or_404(Stage, id=id)

    deployment = Deployment(stage=stage, tasks=stage.tasks)
    return Response(deployment.code, mimetype='application/python')

aurora_app/tasks/views.py
from flask import Blueprint, render_template, request, redirect, url_for

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import notify, get_or_404
from ..stages.models import Stage

from .models import Task
from .forms import TaskForm

tasks = Blueprint('tasks', __name__, url_prefix='/tasks')


@tasks.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_task')
def create():
    stage_id = request.args.get('stage_id', None)
    stage = get_or_404(Stage, id=stage_id) if stage_id else None
    form = TaskForm(stages=[stage])

    if form.validate_on_submit():
        task = Task()
        form.populate_obj(task)
        db.session.add(task)
        db.session.commit()

        notify(u'Task "{0}" has been created.'.format(task.name),
               category='success', action='create_task')
        return redirect(url_for('tasks.view', id=task.id))

    return render_template('tasks/create.html', form=form, stage_id=stage_id)


@tasks.route('/view/<int:id>')
def view(id):
    task = get_or_404(Task, id=id)
    return render_template('tasks/view.html', task=task)


@tasks.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_task')
def edit(id):
    task = get_or_404(Task, id=id)
    form = TaskForm(request.form, task)

    if form.validate_on_submit():
        # Since we don't show deployments in form, we need to set them here.
        form.deployments.data = task.deployments
        form.populate_obj(task)
        db.session.add(task)
        db.session.commit()

        notify(u'Task "{0}" has been updated.'.format(task.name),
               category='success', action='edit_task')
        return redirect(url_for('tasks.view', id=task.id))

    return render_template('tasks/edit.html', task=task, form=form)


@tasks.route('/delete/<int:id>')
@must_be_able_to('delete_task')
def delete(id):
    task = get_or_404(Task, id=id)

    notify(u'Task "{0}" has been deleted.'.format(task.name),
           category='success', action='delete_task')

    db.session.delete(task)
    db.session.commit()

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@tasks.route('/')
def all():
    tasks = Task.query.all()
    return render_template('tasks/all.html', tasks=tasks)

aurora_app/templates/stages/all.html
{% extends 'frontend/index.html' %}

{% block title %}Stages{% endblock %}

{% block content %}
  <ul class='list-unstyled list-inline'>
    <li><h1>Stages</h1></li>
    {% if g.user.can('create_stage') %}
      <li><a href="{{ url_for('stages.create') }}">New</a></li>
    {% endif %}
  </ul>

  <hr />

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Project</th>
      </tr>
    </thead>
    <tbody>
      {% for stage in stages %}
          <tr>
            <td><a href="{{ url_for('stages.view', id=stage.id) }}">{{ stage.name }}</a></td>
            <td>
              {% if stage.project %}
                <ul class="list-unstyled">
                  <li><a href="{{ url_for('projects.view', id=stage.project.id) }}">{{ stage.project }}</a></li>
                </ul>
              {% else %}
                No available project.
              {% endif %}
            </td>
            <td class="small-width"><a href="{{ url_for('stages.edit', id=stage.id) }}">Edit</a></td>
            <td class="small-width"><a href="{{ url_for('stages.delete', id=stage.id, next=url_for('stages.all')) }}" class='delete'>Delete</a></td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block js %}
  {{ super() }}

  <script src="{{ url_for('static', filename='aurora/js/delete_handler.js') }}"></script>
{% endblock %}

aurora_app/templates/stages/create.html
{% extends 'frontend/index.html' %}

{% block title %}Create a new stage{% endblock %}

{% block content %}
  <h1>Create a new stage</h1>
  <hr />
  {% include 'stages/form.html' %}
{% endblock %}

aurora_app/templates/stages/edit.html
{% extends 'frontend/index.html' %}

{% block title %}Edit | {{ stage }}{% endblock %}

{% block content %}
  <h1>Editing stage: 
    {% if stage.project %}
      <a href="{{ url_for('projects.view', id=stage.project.id) }}">{{ stage.project.name }}</a> /
    {% endif %} {{ stage.name }}
  </h1>
  <hr />
  {% include 'stages/form.html' %}
{% endblock %}

aurora_app/templates/stages/form.html
{% import 'helpers/errors.html' as errors %}

<form method="post" action="">
  <fieldset>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class="form-control") }}

      {{ errors.show(form.name) }}
    </div>

    <div class="form-group">
      {{ form.code.label }}
      {{ form.code(class="form-control") }}

      {{ errors.show(form.code) }}
    </div>

    <div class="form-group">
      {{ form.project.label }}
      {{ form.project(class="form-control") }}

      {{ errors.show(form.project) }}
    </div>

    <div class="form-group">
      {{ form.tasks.label }}
      {{ form.tasks(class="form-control") }}

      {{ errors.show(form.tasks) }}
    </div>

    <button class='btn btn-default'>Submit</button>
  </fieldset>
</form>

{% include 'helpers/codemirror.html' %}

aurora_app/templates/stages/table.html
{% extends 'main/index.html' %}

{% block title %}Stages{% endblock %}

{% block content %}
  <ul class='unstyled inline view-title'>
    <li><h1>Stages</h1></li>
  </ul>

  <hr />

  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
    </tr>
  </thead>
  <tbody>
    {% for stage in stages %}
        <tr>
          <td><a href="{{ url_for('stages.view', id=stage.id) }}">{{ stage.name }}</a></td>
          <td>
            {% if stage.project %}
              <ul class="unstyled">
                <li><a href="{{ url_for('projects.view', id=stage.project.id) }}">{{ stage.project }}</a></li>
              </ul>
            {% else %}
              No available project.
            {% endif %}
          </td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

aurora_app/templates/stages/view.html
{% import 'helpers/recent_deployments.html' as recent_deployments %}

{% extends 'frontend/index.html' %}

{% block title %}{{ stage }}{% endblock %}

{% block content %}
  <ul class='list-unstyled list-inline'>
    <li>
      <h1>
        {% if stage.project %}
          <a href="{{ url_for('projects.view', id=stage.project.id) }}">{{ stage.project.name }}</a> /
        {% endif %} {{ stage.name }}
      </h1>
    </li>
    {% if g.user.can('create_deployment') and stage.project %}
      <li><a href="{{ url_for('deployments.create', id=stage.id) }}">Deploy</a></li>
    {% endif %}
    <li><a href="{{ url_for('stages.export', id=stage.id) }}">Export</a></li>
    {% if g.user.can('edit_stage') %}
      <li><a href="{{ url_for('stages.edit', id=stage.id) }}">Edit</a></li>
    {% endif %}
    {% if g.user.can('delete_stage') %}
      <li><a id="delete">Delete</a></li>
    {% endif %}
  </ul>

  <hr />

  <p><strong>Code:</strong></p>
  <pre><code lang="python">{{ stage.code }}</code></pre>

  <ul class='list-unstyled list-inline'>
    <li><h4>Tasks</h4></li>
    {% if g.user.can('create_task') %}
      <li><a href="{{ url_for('tasks.create', stage_id=stage.id) }}">New</a></li>
    {% endif %}
  </ul>

  {% if stage.tasks %}
    <ul>
      {% for task in stage.tasks %}
        <li><a href="{{ url_for('tasks.view', id=task.id) }}">{{ task.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p class='alert'>
      No available tasks.
    </p>
  {% endif %}

  {{ recent_deployments.show(get_recent_deployments(stage)) }}
{% endblock %}

{% block js %}
  {{ super() }}

  <script>
    $(function() {
      $("#delete").click(function() {
        if (confirm("Are you sure?")) {
          document.location.href = "{{ url_for('stages.delete', id=stage.id) }}";
        }
      }); 
    });
  </script>
{% endblock %}