aurora_app/urls.py
from django.conf.urls import include, patterns, url, handler500
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
admin.autodiscover()

handler500 = 'cruiser.views.server_error'

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout', ),
)

urlpatterns += patterns(
    'aurora_app.cruiser.views',
    url(r'^$', 'index', name='index'),
    url(r'^project/(?P<project_id>\d+)$', 'project', name='project'),
    url(r'^project/new$', 'new_project', name='new_project'),
    url(r'^task/(?P<task_id>\d+)$', 'task', name='task'),
    url(r'^task/new$', 'new_task', name='new_task'),
    url(r'^stage/(?P<stage_id>\d+)$', 'stage', name='stage'),
    url(r'^stage/(?P<stage_id>\d+)/(?P<task_id>\d+)/exec$', 'exec_task', name='exec_task'),
    url(r'^stage/new$', 'new_stage', name='new_stage'),
    url(r'^deployment/(?P<deploy_id>\d+)/$', 'monitor', name='deployment_monitor'),
    url(r'^deployment/(?P<deploy_id>\d+)/get_log/$', 'get_log', name='deployment_log'),
    url(r'^deployment/(?P<deploy_id>\d+)/cancel/$', 'cancel', name='cancel_deployment'),
)

urlpatterns += staticfiles_urlpatterns()

aurora_app/frontend/forms.py
from flask.ext.wtf import (Form, Email, Required, TextField, BooleanField,
                           PasswordField)


class LoginForm(Form):
    email = TextField('Email', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required()])
    remember_me = BooleanField('Remember me', default=False)

aurora_app/frontend/views.py
from flask import Blueprint, render_template, redirect, g, url_for, request
from flask.ext.login import login_user, logout_user, current_user

from ..decorators import public
from ..users.models import User
from ..deployments.models import Deployment

from .forms import LoginForm

frontend = Blueprint('frontend', __name__)


@frontend.route('/')
def index():
    deployments = Deployment.query.order_by('started_at desc').limit(10).all()
    return render_template('frontend/index.html', deployments=deployments)


@frontend.route('/login', methods=['GET', 'POST'])
@public
def login():
    if g.user is not None:
        return redirect(url_for('frontend.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.email.data,
                                                form.password.data)
        if user and authenticated:
            if login_user(user, remember=form.remember_me.data):
                return redirect(request.args.get('next') or
                                url_for('frontend.index'))

        form.password.errors = [u'Invalid password.']

    return render_template('frontend/login.html', form=form)


@frontend.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('frontend.index'))

aurora_app/projects/views.py
import json

from flask import Blueprint, render_template, url_for, redirect, request, g

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify

from .models import Project, ProjectParameter
from .exceptions import ParameterValueError
from .forms import ProjectForm
from .tasks import clone_repository, remove_repository

projects = Blueprint('projects', __name__, url_prefix='/projects')


@projects.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_project')
def create():
    form = ProjectForm()

    if form.validate_on_submit():
        project = Project()
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        project.create_default_params()

        notify(u'Project "{0}" has been created.'.format(project.name),
               category='success', action='create_project')
        return redirect(url_for('projects.view', id=project.id))

    return render_template('projects/create.html', form=form)


@projects.route('/view/<int:id>')
def view(id):
    project = get_or_404(Project, id=id)
    return render_template('projects/view.html', project=project)


@projects.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_project')
def edit(id):
    project = get_or_404(Project, id=id)
    form = ProjectForm(request.form, project)

    if form.validate_on_submit():
        form.params.data = project.params
        form.populate_obj(project)
        db.session.add(project)
        db.session.commit()

        notify(u'Project "{0}" has been updated.'.format(project.name),
               category='success', action='edit_project')
        return redirect(url_for('projects.view', id=id))

    return render_template('projects/edit.html', project=project, form=form)


@projects.route('/delete/<int:id>')
@must_be_able_to('delete_project')
def delete(id):
    project = get_or_404(Project, id=id)

    # Delete stages
    for stage in project.stages:
        db.session.delete(stage)
    # Delete params
    for param in project.params:
        db.session.delete(param)
    db.session.delete(project)
    db.session.commit()
    
    notify(u'Project "{0}" has been deleted.'.format(project.name),
           category='success', action='delete_project')

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))

TASKS = {
    'clone_repository': clone_repository,
    'remove_repository': remove_repository
}


@projects.route('/execute/<int:id>', methods=['POST'])
def execute(id):
    project = get_or_404(Project, id=id)
    action = request.form.get('action')
    if g.user.can(action):
        if action == 'edit_project':
            name, value = request.form.get('name'), request.form.get('value')
            parameter = ProjectParameter.query.filter_by(name=name).first()

            try:
                parameter.set_value(value)
                db.session.add(parameter)
                db.session.commit()
            except ParameterValueError as e:
                notify(e.message, category='error', action='edit_project')
                return json.dumps({'error': True})
        else:
            TASKS[action](project)
        return json.dumps({'error': False})

    notify(u"""You can't execute "{0}.{1}".""".format(project.name, action),
           category='error', action=action, user_id=g.user.id)
    return json.dumps({'error': True})


@projects.route('/commits/<int:id>')
def commits(id):
    project = get_or_404(Project, id=id)
    branch = request.args.get('branch')
    query = request.args.get('query')
    page_limit = int(request.args.get('page_limit'))
    page = int(request.args.get('page'))

    if query:
        commits = project.get_all_commits(branch,
                                          skip=page_limit * page)
    else:
        commits = project.get_commits(branch, max_count=page_limit,
                                      skip=page_limit * (page - 1))

    result = []
    for commit in commits:
        if query and not (query in commit.hexsha or query in commit.message):
            continue
        else:
            result.append({'id': commit.hexsha,
                           'message': commit.message,
                           'title': "{0} - {1}".format(commit.hexsha[:10],
                                                       commit.message)})

    total = project.get_commits_count(branch)
    if query:
        total = len(result)
        result = result[:page_limit]

    return json.dumps({'total': total,
                       'commits': result})


@projects.route('/commits/one/<int:id>/<string:branch>/<string:commit>')
def get_one_commit(id, branch, commit):
    project = get_or_404(Project, id=id)
    commits = project.get_all_commits(branch)
    for item in commits:
        if commit == item.hexsha:
            return json.dumps({'id': item.hexsha,
                               'message': item.message,
                               'title': "{0} - {1}".format(item.hexsha[:10],
                                                           item.message)})
    return 'error', 500


@projects.route('/')
def all():
    projects = Project.query.all()
    return render_template('projects/all.html', projects=projects)

aurora_app/stages/views.py
from flask import (Blueprint, render_template, request, redirect, url_for,
                   Response)

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import get_or_404, notify
from ..projects.models import Project
from ..deployments.models import Deployment

from .forms import StageForm
from .models import Stage

stages = Blueprint('stages', __name__, url_prefix='/stages')


@stages.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_stage')
def create():
    project_id = request.args.get('project_id', None)
    project = get_or_404(Project, id=project_id) if project_id else None
    form = StageForm(project=project)

    if form.validate_on_submit():
        stage = Stage()
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been created.'.format(stage),
               category='success', action='create_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/create.html', form=form, id=project_id)


@stages.route('/view/<int:id>')
def view(id):
    stage = get_or_404(Stage, id=id)
    return render_template('stages/view.html', stage=stage)


@stages.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_stage')
def edit(id):
    stage = get_or_404(Stage, id=id)
    form = StageForm(request.form, stage)

    if form.validate_on_submit():
        # Since we don't show deployments in form, we need to set them here.
        form.deployments.data = stage.deployments
        form.populate_obj(stage)
        db.session.add(stage)
        db.session.commit()

        notify(u'Stage "{0}" has been updated.'.format(stage),
               category='success', action='edit_stage')
        return redirect(url_for('stages.view', id=stage.id))

    return render_template('stages/edit.html', stage=stage, form=form)


@stages.route('/delete/<int:id>')
@must_be_able_to('delete_stage')
def delete(id):
    stage = get_or_404(Stage, id=id)

    project_id = stage.project.id if stage.project else None

    notify(u'Stage "{0}" has been deleted.'.format(stage),
           category='success', action='delete_stage')

    db.session.delete(stage)
    db.session.commit()

    if project_id:
        return redirect(url_for('projects.view', id=project_id))

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@stages.route('/')
def all():
    stages = Stage.query.all()
    return render_template('stages/all.html', stages=stages)


@stages.route('/export/<int:id>/fabfile.py')
def export(id):
    stage = get_or_404(Stage, id=id)

    deployment = Deployment(stage=stage, tasks=stage.tasks)
    return Response(deployment.code, mimetype='application/python')

aurora_app/tasks/views.py
from flask import Blueprint, render_template, request, redirect, url_for

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import notify, get_or_404
from ..stages.models import Stage

from .models import Task
from .forms import TaskForm

tasks = Blueprint('tasks', __name__, url_prefix='/tasks')


@tasks.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_task')
def create():
    stage_id = request.args.get('stage_id', None)
    stage = get_or_404(Stage, id=stage_id) if stage_id else None
    form = TaskForm(stages=[stage])

    if form.validate_on_submit():
        task = Task()
        form.populate_obj(task)
        db.session.add(task)
        db.session.commit()

        notify(u'Task "{0}" has been created.'.format(task.name),
               category='success', action='create_task')
        return redirect(url_for('tasks.view', id=task.id))

    return render_template('tasks/create.html', form=form, stage_id=stage_id)


@tasks.route('/view/<int:id>')
def view(id):
    task = get_or_404(Task, id=id)
    return render_template('tasks/view.html', task=task)


@tasks.route('/edit/<int:id>', methods=['GET', 'POST'])
@must_be_able_to('edit_task')
def edit(id):
    task = get_or_404(Task, id=id)
    form = TaskForm(request.form, task)

    if form.validate_on_submit():
        # Since we don't show deployments in form, we need to set them here.
        form.deployments.data = task.deployments
        form.populate_obj(task)
        db.session.add(task)
        db.session.commit()

        notify(u'Task "{0}" has been updated.'.format(task.name),
               category='success', action='edit_task')
        return redirect(url_for('tasks.view', id=task.id))

    return render_template('tasks/edit.html', task=task, form=form)


@tasks.route('/delete/<int:id>')
@must_be_able_to('delete_task')
def delete(id):
    task = get_or_404(Task, id=id)

    notify(u'Task "{0}" has been deleted.'.format(task.name),
           category='success', action='delete_task')

    db.session.delete(task)
    db.session.commit()

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@tasks.route('/')
def all():
    tasks = Task.query.all()
    return render_template('tasks/all.html', tasks=tasks)

aurora_app/users/views.py
from flask import Blueprint, render_template, redirect, url_for, request, g

from ..decorators import must_be_able_to
from ..extensions import db
from ..utils import notify, get_or_404

from .models import User
from .forms import EditUserForm, CreateUserForm

users = Blueprint('users', __name__, url_prefix='/users')


@users.route('/create', methods=['GET', 'POST'])
@must_be_able_to('create_user')
def create():
    form = CreateUserForm()

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        user.set_password(form.password.data)

        # Check for duplicates
        if User.query.filter_by(username=form.username.data).first() is None:
            db.session.add(user)
            db.session.commit()

            notify(u'User "{0}" has been created.'.format(user.username),
                   category='success', action='create_user')
            return redirect(url_for('users.view', id=user.id))
        form.username.errors = [u'Choose another username, please.']

    return render_template('users/create.html', form=form)


@users.route('/view/<int:id>')
def view(id):
    user = get_or_404(User, id=id)
    return render_template('users/view.html', user=user)


@users.route('/')
def all():
    users = User.query.all()
    return render_template('users/all.html', users=users)


@users.route('/delete/<int:id>')
@must_be_able_to('delete_user')
def delete(id):
    user = get_or_404(User, id=id)

    notify(u'User "{0}" has been deleted.'.format(user.username),
           category='success', action='delete_user')

    db.session.delete(user)
    db.session.commit()

    return redirect(request.args.get('next')
                    or url_for('frontend.index'))


@users.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    user = get_or_404(User, id=id)

    if not (g.user.can('edit_user') or user.id == g.user.id):
        notify(u"You can't do that. You don't have permission.",
               category='error', action='edit_user')

        return redirect(request.args.get('next')
                        or request.referrer
                        or url_for('frontend.index'))

    form = EditUserForm(request.form, user)

    if form.validate_on_submit():
        form.populate_obj(user)

        if form.password.data:
            user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        notify(u'User "{0}" has been updated.'.format(user.username),
               category='success', action='edit_user')
        return redirect(url_for('users.view', id=id))

    return render_template('users/edit.html', user=user, form=form)

aurora_app/templates/frontend/index.html
{% extends 'layout.html' %}

{% block title %}Welcome{% endblock %}

{% block nav %}
  <div class="navbar">
      <a class="navbar-brand" href="{{ url_for('frontend.index') }}">Aurora</a>

      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('projects.all') }}">Projects</a></li>
        <li><a href="{{ url_for('stages.all') }}">Stages</a></li>
        <li><a href="{{ url_for('tasks.all') }}">Tasks</a></li>
        <li><a href="{{ url_for('users.all') }}">Users</a></li>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li><a href="{{ url_for('users.view', id=g.user.id) }}"><img src="{{ g.user.email | gravatar(size=16) }}" title="{{ g.user.username }}" /> <strong>{{ g.user.username }}</strong></a></li>
        <li><a href="{{ url_for('notifications.all') }}"><i class="glyphicon glyphicon-exclamation-sign"></i> Notifications</a></li>
        <li><a href="{{ url_for('frontend.logout') }}"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
      </ul>
  </div>
{% endblock %}

{% block body %}
  <div class="container">
    <div class="row indent-bottom">
      <div class="col-lg-3 text-center">
        <ul class='nav nav-pills nav-stacked well'>
          {% if projects %}
            {% for project in projects %}
              <li>
                <a href="{{ url_for('projects.view', id=project.id) }}"><strong>{{ project.name }}</strong></a>
                {% if project.stages %}
                  <ul>
                    {% for stage in project.stages %}
                      <li><a href="{{ url_for('stages.view', id=stage.id) }}">{{ stage.name }}</a></li>
                    {% endfor %}
                  </ul>
                {% else %}
                  <ul>
                    {% if g.user.can('create_stage') %}
                      <li><a href="{{ url_for('stages.create', project_id=project.id) }}">New stage</a></li>
                    {% endif %}
                  </ul>
                {% endif %}
              </li>
            {% endfor %}
          {% else %}
            {% if g.user.can('create_project') %}
              <li><a href="{{ url_for('projects.create') }}"><strong>New project</strong></a></li>
            {% endif %}
          {% endif %}
        </ul>
      </div>
      <div class="col-lg-9">
        {% block notifications %}
          <div id='notifications'>
            <ul class='list-unstyled'>
            </ul>
          </div>
        {% endblock %}

        {% block content %}
          {% if not deployments %}
            <h4 class='alert'>
              No available deployments.
            </h4>
          {% else %}
            <ul class='list-unstyled list-inline'>
              <li><h1>Last deployments</h1></li>
            </ul>

            <hr />

            <ul class='list-unstyled'>
              {% for deployment in deployments %}
                <li>{% include 'deployments/deployment.html' %}</li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

{% block js %}
  {{ super() }}

  <script src="{{ url_for('static', filename='mustache/mustache.js') }}"></script>
  <script src="{{ url_for('static', filename='eventsource/eventsource.js') }}"></script>
  <script>
    $(function () {
      /* Hooks */
      $("#cancel_deployment_button").click(function() {
        var id = $(this).data('id');
        $.ajax({
          url: '{{ url_for('deployments.cancel') }}',
          type: 'POST',
          data: {'id': id}
        });
      });

      /* Notifications settings */
      var notification_template = '<li>\
        <div class="alert alert-{{ '{{category}}' }}">\
          <button type="button" class="close" data-dismiss="alert">&times;</button>\
          {{ '{{message}}' }}\
        </div>\
      </li>';
      var notification_timeout = 4000;

      var eventSource = new EventSource("{{ url_for('notifications.unseen') }}");
      eventSource.onmessage = function(e) {
        var notification = $.parseJSON(e.data);
        var html = Mustache.to_html(notification_template, notification);
        var hiding_html = $(html).show(0).delay(notification_timeout).hide(0);
        $("#notifications").children('ul').append(hiding_html);
      }
    });
  </script>
{% endblock %}

aurora_app/templates/frontend/login.html
{% extends 'layout.html' %}

{% import 'helpers/errors.html' as errors %}

{% block title %}Log in{% endblock %}

{% block body %}
  <div class="navbar text-center">
    <h1>Aurora</h1>
  </div>
  <div class="container">
    <form class="col-lg-4 col-offset-4 form-horizontal" action="" method="post" name="login" >
      <fieldset>
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.email.label(class="col-lg-3 control-label") }}
          <div class="col-lg-6">
            {{ form.email(class="form-control") }}

            {{ errors.show(form.email) }}
          </div>
        </div>

        <div class="form-group">
          {{ form.password.label(class="col-lg-3 control-label") }}
          <div class="col-lg-6">
            {{ form.password(class="form-control") }}

            {{ errors.show(form.password) }}

            <div class="checkbox">
              {{ form.remember_me.label }}
              {{ form.remember_me }}
            </div>

            <button type="submit" class="btn btn-default">Sign In</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
{% endblock %}